GLB HsInv0003
GLB HsInv0004
GLB HsInv0006
GLB HsInv0030
No perfect tag SNPs for HsInv0030 in GLB
GLB HsInv0031
GLB HsInv0040
GLB HsInv0041
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0041_calcGenos' for reading: No such file or directory
GLB HsInv0045
GLB HsInv0055
No perfect tag SNPs for HsInv0055 in GLB
GLB HsInv0058
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0058_calcGenos' for reading: No such file or directory
GLB HsInv0059
GLB HsInv0061
No perfect tag SNPs for HsInv0061 in GLB
GLB HsInv0063
GLB HsInv0068
GLB HsInv0092
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0092_calcGenos' for reading: No such file or directory
GLB HsInv0095
GLB HsInv0097
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 93, in <module>
    gen_sih : consensus[0]
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0097_calcGenos' for reading: No such file or directory
GLB HsInv0098
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0098_calcGenos' for reading: No such file or directory
GLB HsInv0102
No perfect tag SNPs for HsInv0102 in GLB
GLB HsInv0105
No perfect tag SNPs for HsInv0105 in GLB
GLB HsInv0114
No perfect tag SNPs for HsInv0114 in GLB
GLB HsInv0124
No perfect tag SNPs for HsInv0124 in GLB
GLB HsInv0201
GLB HsInv0209
No perfect tag SNPs for HsInv0209 in GLB
GLB HsInv0241
No perfect tag SNPs for HsInv0241 in GLB
GLB HsInv0260
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0260_calcGenos' for reading: No such file or directory
GLB HsInv0266
No perfect tag SNPs for HsInv0266 in GLB
GLB HsInv0284
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0284_calcGenos' for reading: No such file or directory
GLB HsInv0340
No perfect tag SNPs for HsInv0340 in GLB
GLB HsInv0341
No perfect tag SNPs for HsInv0341 in GLB
GLB HsInv0347
No perfect tag SNPs for HsInv0347 in GLB
GLB HsInv0379
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 93, in <module>
    gen_sih : consensus[0]
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0379_calcGenos' for reading: No such file or directory
GLB HsInv0790
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 93, in <module>
    gen_sih : consensus[0]
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/GLB/HsInv0790_calcGenos' for reading: No such file or directory
EUR HsInv0003
EUR HsInv0004
EUR HsInv0006
EUR HsInv0030
No perfect tag SNPs for HsInv0030 in EUR
EUR HsInv0031
EUR HsInv0040
EUR HsInv0041
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0041_calcGenos' for reading: No such file or directory
EUR HsInv0045
EUR HsInv0055
No perfect tag SNPs for HsInv0055 in EUR
EUR HsInv0058
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0058_calcGenos' for reading: No such file or directory
EUR HsInv0059
EUR HsInv0061
No perfect tag SNPs for HsInv0061 in EUR
EUR HsInv0063
EUR HsInv0068
EUR HsInv0092
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 93, in <module>
    gen_sih : consensus[0]
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0092_calcGenos' for reading: No such file or directory
EUR HsInv0095
EUR HsInv0097
No perfect tag SNPs for HsInv0097 in EUR
EUR HsInv0098
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0098_calcGenos' for reading: No such file or directory
EUR HsInv0102
No perfect tag SNPs for HsInv0102 in EUR
EUR HsInv0105
EUR HsInv0114
No perfect tag SNPs for HsInv0114 in EUR
EUR HsInv0124
No perfect tag SNPs for HsInv0124 in EUR
EUR HsInv0201
EUR HsInv0209
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0209_calcGenos' for reading: No such file or directory
EUR HsInv0241
No perfect tag SNPs for HsInv0241 in EUR
EUR HsInv0260
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 142, in <module>
    'Genotype' : ranking.index.tolist()[0],
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0260_calcGenos' for reading: No such file or directory
EUR HsInv0266
No perfect tag SNPs for HsInv0266 in EUR
EUR HsInv0284
No perfect tag SNPs for HsInv0284 in EUR
EUR HsInv0340
Traceback (most recent call last):
  File "code/python/tagSNPcheck.py", line 93, in <module>
    gen_sih : consensus[0]
IndexError: list index out of range
tail: cannot open 'tmp/2020-12-18_08_tagsnps/EUR/HsInv0340_calcGenos' for reading: No such file or directory
EUR HsInv0341
No perfect tag SNPs for HsInv0341 in EUR
EUR HsInv0347
No perfect tag SNPs for HsInv0347 in EUR
EUR HsInv0379
No perfect tag SNPs for HsInv0379 in EUR
EUR HsInv0790
No perfect tag SNPs for HsInv0790 in EUR
No sample individuals were found for EAS population in data/use/avery_individuals/nc17nc18
No sample individuals were found for SAS population in data/use/avery_individuals/nc17nc18
No sample individuals were found for AFR population in data/use/avery_individuals/nc17nc18
